server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
    shutdown:
      enabled: true
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
