server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    department:
      path: /api/department/**
      serviceId: department-service
    employee:
      path: /api/employee/**
      serviceId: employee-service
    organization:
      path: /api/organization/**
      serviceId: organization-service
